### ISSUE TITLE
Roster Bug

### ISSUE THREAD

**Issue by Raajheer1** [ZJX-ARTCC/jacksonville-issue-tracker#23]
**Describe the bug**
---
Name: Raaj Patel : http://prntscr.com/12bivyc
CID: 1293257
Rating: I3
Home ARTCC: ZDV
Certifications: http://prntscr.com/12biw9c

I am able to log in to the website, my user displays with my training notes, controller stats, and ratings. However, when I look at the roster my name is nowhere to be found.

**To Reproduce**
---
1. Look at the roster
2. Look at my account dashboard

**Expected behavior**
---
I'm guessing if I'm not on the roster anymore I shouldn't be able to log in at all correct? I know at least I shouldn't have any controlling certs.

**Screenshots**
---
![image](https://user-images.githubusercontent.com/41763998/116740572-d192c480-a9ba-11eb-8f6c-cceac4ba2e61.png)
![image](https://user-images.githubusercontent.com/41763998/116740601-dce5f000-a9ba-11eb-9766-9b6646bdba7d.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome
 - Latest

**Comment by brinbrody** [comment]
Not a bug. User was removed from roster for inactivity at the end of Q1 2021 (activity requirements NOT met).

Contact ZJX DATM (datm@zjxartcc.org) with questions. 

---

Editing for clarity (since I missed your comment): All VATSIM users may log into the ZJX website regardless of their membership status.  An authenticated session is required to leave feedback and to apply as a visitor. This is functioning as intended.
